#!/bin/bash

# check if we already added signature
grep -q "Acting on behalf of Daimler TSS GmbH" $1


if ! grep -q "Acting on behalf of" $1; then
  sed -i.bak -e "1s/^/\n\nActing on behalf of Daimler TSS GmbH - https:\/\/www.daimler-tss\.com\/de\/impressum\/\nAnd licensed under MIT/" $1
fi

